# =========================================================
# ~/.bashrc — Modular & Engineering Friendly
# generated by ChatGPT - 2026.04.06 16:05
# =========================================================

# ---------------------------------------------------------
# 1. Interactive Shell Check
# ---------------------------------------------------------
[[ $- != *i* ]] && return

# ---------------------------------------------------------
# 2. Environment Variables
# ---------------------------------------------------------
export EDITOR="code"
export VISUAL="code"
export PAGER="less"

# History configuration (important for dev workflow)
export HISTCONTROL=ignoredups:erasedups
export HISTSIZE=10000
export HISTFILESIZE=20000
export HISTTIMEFORMAT="%F %T "

# Append to history, don’t overwrite
shopt -s histappend

# Update history after every command
PROMPT_COMMAND="history -a; history -c; history -r; $PROMPT_COMMAND"

#----------------------------------------------------------
# 3. Safety & Defaults
# ---------------------------------------------------------
set -o noclobber   # prevent overwriting files with >
shopt -s checkwinsize
shopt -s autocd    # cd without typing cd

# ---------------------------------------------------------
# 4. Aliases (General)
# ---------------------------------------------------------
alias ls='ls --color=auto -F'
alias ll='ls -la' #-lah
alias la='ls -A'
alias l='ls -CF'
#alias ld='ll -d .[^.]* ..?*' # executed with error! to be fixed
alias grep='grep --color=auto'

# safer file operations
alias nv='nvim'
alias cp='cp -i'
alias mv='mv -i'
alias rm='rm -i'

# ---------------------------------------------------------
# 5. Navigation Shortcuts
# ---------------------------------------------------------
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'

# Quick jump (edit paths to your workflow)
alias one='cd ~/home/mawn/OneWareStudio/Projects/myFirstOneWareProject'
alias uno='cd ~/Documents/GitWSinEOS/rpi4_to_uno/'
alias rpi4='ssh -p 22 mawn@rpi4-homelab'

alias dot='cd ~/dotfiles'
#alias proj='cd ~/projects'
#alias fpga='cd ~/projects/fpga'
#alias embedded='cd ~/projects/embedded'

# ---------------------------------------------------------
# 6. Git Productivity
# ---------------------------------------------------------
alias g='git'
alias gs='git status'
alias ga='git add'
alias gc='git commit'
alias gp='git push'
alias gl='git pull'
alias gd='git diff'
alias gb='git branch'
alias lg='git log --oneline --graph --all'
alias gcm='git commit -m'

# ---------------------------------------------------------
# 7. Development Helpers
# ---------------------------------------------------------

# Create and enter directory
mkcd() {
    mkdir -p "$1" && cd "$1"
}
# ---------------------------------------------------------
# 8. Prompt (Starship)
# ---------------------------------------------------------
eval "$(starship init bash)"

# ---------------------------------------------------------
# 9. Local Overrides (Machine-specific config)
# ---------------------------------------------------------
[ -f ~/.bashrc.local ] && source ~/.bashrc.local

# Created by `pipx` on 2026-04-13 18:51:05
export PATH="$PATH:/home/mawn/.local/bin"
